return {
--	"nvimtools/none-ls.nvim",
--	dependencies = {
--		"nvim-lua/plenary.nvim",
--	},
--	opts = function()
--		local null_ls = require("null-ls")
--
--		return {
--			sources = {
--				null_ls.builtins.formatting.stylua,
--			},
			--			on_attach = function(client, bufnr)
			--				local augroup = vim.api.nvim_create_augroup("LspFormatting", {})
			--				if client.supports_method("textDocument/formatting") then
			--					vim.api.nvim_clear_autocmds({ group = augroup, buffer = bufnr })
			--					vim.api.nvim_create_autocmd("BufWritePre", {
			--						group = augroup,
			--						buffer = bufnr,
			--						callback = function()
			--							vim.lsp.buf.format({ async = false })
			--						end,
			--					})
			--				end
			--			end,
	--	}
	--end,
}
